services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql

  app:
     image: 42crunch/pixi:v4.7
     container_name: pixiapi
     depends_on:
     - db
     ports:
       - "8090:8090"
     expose:
       - 8090
volumes:
  data: